

version: "2"

networks:
  superhero:

services:

  orderer.hydratings.com:

    container_name: orderer.hydratings.com

    extends:
      file: ./docker/orderer-base.yaml
      service: orderer-base

    volumes:
    - ./crypto-config/ordererOrganizations/hydratings.com/orderers/orderer.hydratings.com/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/hydratings.com/orderers/orderer.hydratings.com/tls:/var/hyperledger/orderer/tls

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric

    command: orderer
    networks:
      - superhero

  batman.hydratings.com:

    container_name: batman.hydratings.com

    extends:
      file: ./docker/core-base.yaml
      service: peer-base

    environment:
        - CORE_PEER_ID=batman.hydratings.com             
        - CORE_PEER_ADDRESS=batman.hydratings.com:7051
        - CORE_PEER_GOSSIP_BOOTSTRAP=batman.hydratings.com:7051
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=batman.hydratings.com:7051
        - CORE_PEER_LOCALMSPID=hydratingsMSP

    volumes:
        - ./crypto-config/peerOrganizations/hydratings.com/peers/batman.hydratings.com/msp:/var/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/hydratings.com/peers/batman.hydratings.com/tls:/var/hyperledger/peer/tls

    command: peer node start

    ports:
      - 7051:7051
      - 7053:7053

    networks:
      - superhero

  superman.ggnratings.com:
  
    container_name: superman.ggnratings.com

    extends:
      file: ./docker/core-base.yaml
      service: peer-base

    environment:
        - CORE_PEER_ID=superman.ggnratings.com        
        - CORE_PEER_ADDRESS=superman.ggnratings.com:7051
        - CORE_PEER_GOSSIP_BOOTSTRAP=wolverine.ggnratings.com:7051
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=wolverine.ggnratings.com:7051
        - CORE_PEER_LOCALMSPID=ggnratingsMSP

    volumes:
        - ./crypto-config/peerOrganizations/ggnratings.com/peers/superman.ggnratings.com/msp:/var/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/ggnratings.com/peers/superman.ggnratings.com/tls:/var/hyperledger/peer/tls

    command: peer node start

    ports:
      - 8051:7051
      - 8053:7053

    networks:
      - superhero

  wolverine.ggnratings.com:
  
    container_name: wolverine.ggnratings.com

    extends:
      file: ./docker/core-base.yaml
      service: peer-base

    environment:
        - CORE_PEER_ID=wolverine.ggnratings.com        
        - CORE_PEER_ADDRESS=wolverine.ggnratings.com:7051
        - CORE_PEER_GOSSIP_BOOTSTRAP=wolverine.ggnratings.com:7051
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=wolverine.ggnratings.com:7051
        - CORE_PEER_LOCALMSPID=ggnratingsMSP

    volumes:
        - ./crypto-config/peerOrganizations/ggnratings.com/peers/wolverine.ggnratings.com/msp:/var/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/ggnratings.com/peers/wolverine.ggnratings.com/tls:/var/hyperledger/peer/tls

    command: peer node start

    ports:
      - 9051:7051
      - 9053:7053

    networks:
      - superhero


  cli:
      container_name: cli
      image: hyperledger/fabric-tools:1.4.1
      tty: true
      stdin_open: true
      environment:
        - GOPATH=/opt/gopath
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        #- FABRIC_LOGGING_SPEC=DEBUG
        - FABRIC_LOGGING_SPEC=INFO
        - CORE_PEER_ID=cli
        - CORE_PEER_ADDRESS=batman.hydratings.com:7051
        - CORE_PEER_LOCALMSPID=hydratingsMSP
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/peer/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/peer/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/peer/tls/ca.crt
        - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp/peerOrganizations/hyd.spratings.com/users/Admin@hyd.spratings.com/msp
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      command: /bin/bash
      volumes:
          - /var/run/:/host/var/run/
          - ./chaincode/:/opt/gopath/src/github.com/chaincode
          - ./crypto-config/peerOrganizations/hydratings.com/peers/batman.hydratings.com/msp:/var/hyperledger/peer/msp
          - ./crypto-config/peerOrganizations/hydratings.com/peers/batman.hydratings.com/tls:/var/hyperledger/peer/tls          
          - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
          - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      depends_on:
          - orderer.hydratings.com
          - batman.hydratings.com
          - superman.hydratings.com
          - wolverine.ggnratings.com
      networks:
        - ratings
